import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "./provider/theme.provider";
import { ThemeToggle } from "./components/ThemeToggle";
import { AuthProvider } from "@/contexts/auth.context";

import { Poppins } from "next/font/google";
import RouterLoadingProvider from "./provider/router.provider";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // whatever you need
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppins.variable} font-poppins antialiased`}
        suppressHydrationWarning
      >
        <ThemeProvider>
          <AuthProvider>
            <RouterLoadingProvider>
              <ThemeToggle />
              {children}
            </RouterLoadingProvider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
