// config/env.config.ts
export const env = {
  PORT: Number(process.env.PORT) || 5000,
  MONGO_URI: process.env.MONGO_URI!,
  JWT_ACCESS_SECRET: process.env.JWT_ACCESS_SECRET!,
  JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET!,
  CLIENT_URL: process.env.CLIENT_URL!,
  SENDER_EMAIL: process.env.SENDER_EMAIL!,
  PASSKEY: process.env.PASSKEY!,
  REDIS_URL: process.env.REDIS_URL!,
  NODE_ENV: process.env.NODE_ENV!,
  RESET_PASS_URL: process.env.RESET_PASS_URL!,
  AWS_REGION: process.env.AWS_REGION!,
  S3_BUCKET_NAME: process.env.S3_BUCKET_NAME!,
  AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID!,
  AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY!,
  ERROR_LOG_RETENTION_PERIOD: process.env.ERROR_LOG_RETENTION_PERIOD!,
  START_INTERVAL: process.env.START_INTERVAL!,
  END_INTERVAL: process.env.END_INTERVAL!,
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY!,
  WEBHOOK_SECRET: process.env.WEBHOOK_SECRET!,
  COOKIE_MAX_AGE: process.env.COOKIE_MAX_AGE!,
};
